export const products = [
  {
    id: 1,
    name: 'Premium Wireless Headphones',
    price: 89.99,
    category: 'Electronics',
    rating: 4.5,
    reviews: 128,
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500&h=500&fit=crop',
    description: 'High-quality wireless headphones with active noise cancellation, 30-hour battery life, and premium sound quality.',
    features: ['Noise Cancellation', 'Battery 30hrs', 'Bluetooth 5.0', 'Foldable Design'],
  },
  {
    id: 2,
    name: 'Smartwatch Pro',
    price: 199.99,
    category: 'Electronics',
    rating: 4.7,
    reviews: 256,
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500&h=500&fit=crop',
    description: 'Advanced smartwatch with health tracking, GPS, and waterproof design for active lifestyles.',
    features: ['Heart Rate Monitor', 'GPS', 'Waterproof', '7-day Battery'],
  },
  {
    id: 3,
    name: '4K Webcam',
    price: 129.99,
    category: 'Electronics',
    rating: 4.6,
    reviews: 189,
    image: 'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=500&h=500&fit=crop',
    description: 'Professional 4K webcam for streaming and video conferences with crystal-clear video quality.',
    features: ['4K Resolution', 'Auto Focus', 'Built-in Mic', 'Wide Angle'],
  },
  {
    id: 4,
    name: 'Portable SSD',
    price: 159.99,
    category: 'Storage',
    rating: 4.8,
    reviews: 342,
    image: 'https://images.unsplash.com/photo-1579465905552-f151f18f4e3f?w=500&h=500&fit=crop',
    description: '500GB ultra-fast portable SSD with USB-C connectivity for quick data transfers.',
    features: ['500GB Storage', 'USB-C', 'Fast Transfer', 'Durable'],
  },
  {
    id: 5,
    name: 'Mechanical Keyboard',
    price: 79.99,
    category: 'Peripherals',
    rating: 4.4,
    reviews: 201,
    image: 'https://images.unsplash.com/photo-1587829191301-5f86e1660149?w=500&h=500&fit=crop',
    description: 'RGB mechanical gaming keyboard with customizable switches and premium build quality.',
    features: ['Mechanical Switches', 'RGB Lighting', 'Programmable', 'Wireless'],
  },
  {
    id: 6,
    name: 'Gaming Mouse',
    price: 59.99,
    category: 'Peripherals',
    rating: 4.6,
    reviews: 175,
    image: 'https://images.unsplash.com/photo-1527814050087-3794c11ff38b?w=500&h=500&fit=crop',
    description: 'Precision gaming mouse with adjustable DPI and ergonomic design for extended gaming sessions.',
    features: ['16000 DPI', 'Ergonomic', 'Fast Response', 'Lightweight'],
  },
  {
    id: 7,
    name: 'USB-C Hub',
    price: 49.99,
    category: 'Accessories',
    rating: 4.5,
    reviews: 134,
    image: 'https://images.unsplash.com/photo-1625948515291-69613efd103f?w=500&h=500&fit=crop',
    description: 'Multi-port USB-C hub with HDMI, USB 3.0, and SD card reader for ultimate connectivity.',
    features: ['7 Ports', 'USB 3.0', 'HDMI 4K', 'SD Card Reader'],
  },
  {
    id: 8,
    name: 'Laptop Stand',
    price: 39.99,
    category: 'Accessories',
    rating: 4.3,
    reviews: 98,
    image: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=500&h=500&fit=crop',
    description: 'Adjustable aluminum laptop stand for better ergonomics and improved cooling.',
    features: ['Adjustable Height', 'Aluminum', 'Portable', 'Supports 17"'],
  },
  {
    id: 9,
    name: 'Monitor Light Bar',
    price: 69.99,
    category: 'Lighting',
    rating: 4.7,
    reviews: 212,
    image: 'https://images.unsplash.com/photo-1559028615-cd4628902d4a?w=500&h=500&fit=crop',
    description: 'Premium monitor light bar that reduces eye strain and provides auto-dimming feature.',
    features: ['Auto Dimming', 'USB Power', 'No Glare', 'Eye Care'],
  },
  {
    id: 10,
    name: 'Wireless Charger',
    price: 24.99,
    category: 'Accessories',
    rating: 4.4,
    reviews: 156,
    image: 'https://images.unsplash.com/photo-1591290621615-cd4628902d4a?w=500&h=500&fit=crop',
    description: 'Fast wireless charging pad compatible with all Qi-enabled devices.',
    features: ['Fast Charging', 'Qi Compatible', 'Non-Slip Base', 'LED Indicator'],
  },
  {
    id: 11,
    name: 'HDMI Cable',
    price: 14.99,
    category: 'Cables',
    rating: 4.2,
    reviews: 89,
    image: 'https://images.unsplash.com/photo-1611532736579-6b16e2b50449?w=500&h=500&fit=crop',
    description: '2m premium HDMI 2.1 cable with 4K@60Hz support and gold-plated connectors.',
    features: ['2 Meters', '4K Support', 'Gold Plated', 'Durable'],
  },
  {
    id: 12,
    name: 'Cable Organizer',
    price: 19.99,
    category: 'Accessories',
    rating: 4.1,
    reviews: 67,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500&h=500&fit=crop',
    description: 'Organize your desk cables with this sleek cable management system.',
    features: ['5 Slots', 'Silicone Material', 'Adhesive Base', 'Easy Clean'],
  },
  {
    id: 13,
    name: 'External Hard Drive',
    price: 99.99,
    category: 'Storage',
    rating: 4.5,
    reviews: 223,
    image: 'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=500&h=500&fit=crop',
    description: '2TB external hard drive for reliable backup and data storage.',
    features: ['2TB Capacity', 'USB 3.0', 'Portable', 'Durable'],
  },
  {
    id: 14,
    name: 'Monitor Mount',
    price: 54.99,
    category: 'Accessories',
    rating: 4.6,
    reviews: 145,
    image: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=500&h=500&fit=crop',
    description: 'Adjustable monitor mount for dual monitors with full articulation.',
    features: ['Dual Monitor', 'Full Articulation', 'VESA Compatible', 'Easy Install'],
  },
  {
    id: 15,
    name: 'USB Desk Fan',
    price: 22.99,
    category: 'Cooling',
    rating: 4.3,
    reviews: 101,
    image: 'https://images.unsplash.com/photo-1585514191589-4e1b54fcac48?w=500&h=500&fit=crop',
    description: 'Compact USB-powered desk fan for keeping your workspace cool.',
    features: ['USB Powered', 'Quiet', 'Adjustable', 'Compact'],
  },
];

export const categories = [
  'All',
  'Electronics',
  'Storage',
  'Peripherals',
  'Accessories',
  'Lighting',
  'Cables',
  'Cooling',
];
